-- create database Snitch_Clothing_Sales;
-- use Snitch_Clothing_Sales;

-- create table Products (
-- ProductID varchar (10) primary key ,
-- Product_Name varchar (150) not null,
-- Product_Category varchar (100),
-- Unit_Price decimal ( 10,2),
-- Segment Varchar (10)
-- );

-- -- 2nd tables

-- create table Customer (
-- CustomerID varchar (10) primary key ,
--  Customer_Name varchar (100),
--  Email varchar (250),
--  Gender varchar(10),
--  Age decimal (10,2),
--  City varchar (100)
--  );
--  
--  -- 3rd table
--  
--  create table Orders (
--  Order_ID int auto_increment primary key,
--  CustomerID varchar (10),
--  ProductID varchar (10),
--  Order_Date date ,
--  Units_Sold int ,
--  Total_Amount int,
--  FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
--  FOREIGN KEY (ProductID) REFERENCES Products(ProductID)
-- );

select * From Products;
select * from Customer;
select * from Orders;

-- Import Data into Tables
-- 1st Products
-- 2nd Customer
-- 3rd Orders

-- ==========================================
-- 25 MySQL QUESTIONS & ANSWERS
-- Snitch Fashion Sales Database Project
-- ==========================================

-- **BASIC QUERIES (1-5)**

-- Q1. Retrieve all customer details from the Customers table.
SELECT * FROM Customer;


-- Q2. List all products with their prices in descending order.
SELECT Product_Name, Unit_Price
FROM Products 
ORDER BY Unit_Price DESC;


-- Q3. Find all customers from a specific city (e.g., Mumbai).
SELECT Customer_Name, Email, City 
FROM Customer 
WHERE City = 'Mumbai';


-- Q4. Get the count of total orders placed.
SELECT COUNT(*) AS Total_Orders 
FROM orders;


-- Q5. Display all unique product categories.
SELECT DISTINCT Product_Category 
FROM Products;


-- **AGGREGATE FUNCTIONS (6-10)**

-- Q6. Calculate the total revenue generated from all sales.
SELECT SUM(Total_Amount) AS Total_Revenue 
FROM orders;


-- Q7. Find the average age of customers.
SELECT AVG(Age) AS Average_Age 
FROM Customer;


-- Q8. Count the number of male and female customers.
SELECT Gender, COUNT(*) AS Customer_Count 
FROM Customer
GROUP BY Gender;


-- Q9. Find the maximum and minimum unit price of products.
SELECT 
    Max(Unit_Price) AS Max_Price, 
    min(unit_Price) AS Min_Price 
FROM products;


-- Q10. Calculate the total units sold for each product.
SELECT p.Product_Name, 
 sum(o.Units_Sold) As Total_Units_Sold
From orders o
join products p on o.ProductID = p.ProductID
group by p.Product_Name
Order By Total_Units_Sold desc;


-- **JOIN QUERIES (11-15)**

-- Q11. Display order details with customer names.
SELECT 
    o.Order_ID,
    c.Customer_Name,
    o.Order_Date,
    o.Total_Amount
    from orders o
    join Customer c on o.CustomerID = c.CustomerID;
    
    
    -- Q12. List all orders with product names and categories.
SELECT 
o.Order_ID,
p.Product_Name,
p.Product_Category,
o.Units_Sold,
o.Total_Amount
From orders o
join products p on o.ProductID = p.ProductID;


-- Q13. Find the total revenue generated by each customer.
SELECT 
c.Customer_Name,

Sum(o.Total_Amount) As Total_Revenue 
From orders o 
join customer c  on o.CustomerID = c.CustomerID
group by c.Customer_Name
order by Total_Revenue desc;
 

-- Q14. Show the top 5 customers who spent the most.
select
c.Customer_Name,
Sum(o.Total_Amount) As Total_Spent
From orders o 
join customer c  on o.CustomerID = c.CustomerID
group by c.Customer_Name 
order by Total_Spent desc
limit 5;


-- Q15. Display sales data with complete customer and product information.
SELECT 
    o.Order_ID,
    c.Customer_Name,
    c.Gender,
    c.Age,
    c.City,
    p.Product_Name,
    p.Product_Category,
    o.Order_Date,
    o.Units_Sold,
    o.Total_Amount
    from orders o
    join customer c on o.CustomerID = c.CustomerID
    join products p on p.ProductID = o.ProductID;
    
    
    -- **ADVANCED AGGREGATE QUERIES (16-20)**

-- Q16. Find the revenue generated by each product category.
SELECT 
p.Product_Category, 
    SUM(o.Total_Amount) AS Category_Revenue,
    COUNT(o.Order_ID) AS Total_Orders
FROM orders o
JOIN Products p ON o.ProductID = p.ProductID
GROUP BY p.Product_Category
ORDER BY Category_Revenue DESC;


-- Q17. Calculate the average order value per customer.
SELECT 
c.Customer_Name,
    AVG(o.Total_Amount) AS Avg_Order_Value,
    COUNT(o.Order_ID) AS Total_Orders
FROM orders o
JOIN Customer c ON o.CustomerID = c.CustomerID
GROUP BY c.Customer_Name
ORDER BY Avg_Order_Value DESC;


-- Q18. Find cities with the highest total sales.
SELECT 
c.City,
sum(o.Total_Amount) as CTS
 from orders o
join customer c on o.CustomerID = c.CustomerID
group by c.City
order by CTS desc;


-- Q19. Identify the most popular product segment by units sold.
SELECT 
p.Segment,
sum(o.Units_Sold) As T_Units,
sum(o.Total_Amount) As T_Revenue
from orders o
join products p on o.ProductID = p.ProductID
group by p.Segment 
order by T_Units desc;


-- Q20. Find the age group distribution of customers and their spending.
select 
case 
when c.Age <25 then '18-24'
when c.Age between 25  and 34 then "25-34"
when c.Age between  35 and 44 then '35-44'
when c.Age between 45 And 54 then '45-54'
else '55+'
end As Age_Group,
count(c.CustomerID) as Customer_Count,
sum(o.Total_Amount) as Total_spend,
avg(o.Total_Amount) As Avg_value
from orders o
join customer c on o.CustomerID = c.CustomerID
group by Age_Group
order by Age_Group desc;


-- Q21. Find customers who have made more purchases.
SELECT 
    c.Customer_Name,
    COUNT(o.Order_ID) AS P_Count,
    SUM(o.Total_Amount) AS Total_Spent
FROM customer c
JOIN orders o ON c.CustomerID = o.CustomerID
GROUP BY c.Customer_Name, c.Email
HAVING COUNT(o.Order_ID) 
ORDER BY P_Count DESC;


-- Q22. Identify products with no sales (if any).
SELECT p.Product_Name, p.Product_Category
FROM Products p
LEFT JOIN orders o ON p.ProductID = o.ProductID
WHERE o.ProductID IS NULL;


-- Q23. Find products that generated revenue above the average product revenue.
SELECT 
    p.Product_Name,
    p.Product_Category,
    SUM(o.Total_Amount) AS Product_Revenue
FROM orders o
JOIN Products p ON o.ProductID = p.ProductID
GROUP BY p.Product_Name, p.Product_Category
HAVING SUM(o.Total_Amount) > (
    SELECT AVG(Product_Revenue)
    FROM (
        SELECT SUM(Total_Amount) AS Product_Revenue
        FROM orders o
        GROUP BY ProductID
    ) AS AvgRevenue
)
ORDER BY Product_Revenue DESC;


-- Q24. Find the gender-wise revenue contribution.
SELECT 
    c.Gender,
    SUM(o.Total_Amount) AS Total_Revenue,
    COUNT(o.Order_ID) AS Total_Orders,
    AVG(o.Total_Amount) AS Avg_Order_Value
FROM Customer c
JOIN orders o  ON c.CustomerID = o.CustomerID
GROUP BY c.Gender;


-- Q25. Identify customers who purchased from multiple product categories.
SELECT 
    c.Customer_Name,
    COUNT(DISTINCT p.Product_Category) AS Categories_Purchased,
    SUM(o.Total_Amount) AS Total_Spent
FROM Customer c
JOIN orders o ON c.CustomerID = o.CustomerID
JOIN Products p ON o.ProductID = p.ProductID
GROUP BY c.Customer_Name
HAVING COUNT(DISTINCT p.Product_Category) > 1
ORDER BY Categories_Purchased DESC;